const FOR_HUMAN_EYE = true;

const MINIMUN_ASTEROIDS_COUNT = 10;
const POPULATION_GAMES = FOR_HUMAN_EYE ? 10 : 50;
const ELITISM = Math.round(0.5 * POPULATION_GAMES);
const MUTATION_RATE = 0.3;
const MUTATION_AMOUNT = 3;

const BIG_ASTEROID = 5;
const MEDIUM_ASTEROID = 10;
const SMALL_ASTEROID = 15;