let FOR_HUMAN_EYE = false;

const MINIMUN_ASTEROIDS_COUNT = 10;
const POPULATION_GAMES = FOR_HUMAN_EYE ? 10 : 20;
const ELITISM = Math.round(0.2 * POPULATION_GAMES);
const MUTATION_RATE = 0.3;
const MUTATION_AMOUNT = 5;

const BIG_ASTEROID = 10;
const MEDIUM_ASTEROID = 20;
const SMALL_ASTEROID = 100;
const MOVEMENT = 0;